/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  apiSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'schema',
      label: 'Schema',
    },
    {
      type: 'category',
      label: 'Api',
      collapsed: false,
      items: [
        {
          type: 'doc',
          label: 'Class',
          id: 'api/class',
        },
        {
          type: 'doc',
          label: 'Race',
          id: 'api/race',
        },
        {
          type: 'doc',
          label: 'Specialization',
          id: 'api/specialization',
        },
        {
          type: 'doc',
          label: 'Trait',
          id: 'api/trait',
        },
        {
          type: 'doc',
          label: 'Feature',
          id: 'api/feature',
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
}
